# This is a basic workflow to help you get started with Actions

name: Update feed

# Controls when the action will run. 
on:
  schedule:
    - cron: '0 * * * *'
      
jobs:
  update-readme-commits:
    name: Update repo readme with latest commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: GITHUB
          feel_list: "https://github.com/junqili259.atom"
